<a href="https://colab.research.google.com/github/samaneh-m/TU-deep-Learning/blob/main/python_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning, Python Tutorial

This is an introductory practice sheet designed to help you get familiar with basic Python programming concepts. Please note the following points:


- This sheet is **not mandatory** and will not be handed in or scored. It is solely intended for your personal learning and practice.
- An example solution will be released one week after the release date of this sheet.



# Task 1: Basics

## Part 1: Function Definitions and Loops

### 1.1 Multiplication Table Function
Write a function `multiplication_table(n)` that:
- Takes a single integer `n` as an argument.
- Uses a `for` loop to print the multiplication table for `n` (from `n x 1` up to `n x 10`).

**Example:**
```python
multiplication_table(5)
```

**Expected Output:**
```
5 x 1 = 5
5 x 2 = 10
...
5 x 10 = 50
```


In [2]:
def multiplication_table(n):
  for i in range(1, 11):
    product = n * i
    print(f"{n} x {i} = {product}")


# Example output for multiplication_table(5)
multiplication_table(5)


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


### 1.2 Sum of Odd Numbers with a While Loop
Write a function `sum_of_odds(limit)` that:
- Takes an integer `limit` as an argument.
- Uses a `while` loop to calculate the sum of all odd numbers from `1` up to `limit` (inclusive).
- Returns the sum.

**Example:**
```python
sum_of_odds(10)
```

**Expected Output:** `25` (1 + 3 + 5 + 7 + 9)

In [7]:
def sum_of_odds(limit):
    current_number = 1
    total_sum = 0
    while current_number <= limit:
        if current_number % 2 != 0:
            total_sum += current_number
        current_number += 1
    return total_sum


print(sum_of_odds(10))


25


## Part 2: Working with Lists

### 1.3 Sorting and Filtering a List of Numbers
Write a function `process_numbers(numbers)` that:
- Takes a list of integers `numbers` as an argument.
- Sorts the list in ascending order.
- Filters out any even numbers and returns a new list with only the odd numbers.

**Example:**
```python
process_numbers([5, 2, 8, 3, 1, 4])
```

**Expected Output:** `[1, 3, 5]`

In [14]:
def process_numbers(number):
  number.sort()
  odd_number = []
  for num in number:
    if num %2 !=0:
      odd_number.append(num)
  return odd_number


process_numbers([8, 9, 2, 3, 5, 5])

[3, 5, 5, 9]

In [11]:
def process_numbers(numbers):
  numbers.sort()
  odd_numbers = []
  for num in numbers:
    if num %2 !=0:
      odd_numbers.append(num)
  return odd_numbers



process_numbers([5, 2, 8, 3, 1, 4])

[1, 3, 5]

### 1.4 Counting Occurrences in a List
Write a function `count_occurrences(elements)` that:
- Takes a list `elements` as an argument.
- Uses a dictionary to count the occurrences of each unique element in the list.
- Returns the dictionary of counts.

**Example:**
```python
count_occurrences(['apple', 'banana', 'apple', 'orange', 'banana', 'apple'])
```

**Expected Output:**
```python
{'apple': 3, 'banana': 2, 'orange': 1}
```

In [18]:
def count_occurances(elements):
  count = {}
  for item in elements:
    if item in count:
      count [item] +=1
    else:
      count [item] = 1
  return count

count_occurances(['apple', 'banana', 'apple', 'orange', 'orange', 'banana', 'apple'])

{'apple': 3, 'banana': 2, 'orange': 2}

In [ ]:
def count_occurrences(elements):
    '''your code'''



count_occurrences(['apple', 'banana', 'apple', 'orange', 'banana', 'apple'])



## Part 3: List Comprehension, Map, and Filter

### Task 1.5: List Comprehension - Squares of Odd Numbers
Write a function `squares_of_odds(limit)` that:
- Takes an integer `limit` as an argument.
- Uses list comprehension to create a list of squares of all odd numbers from `0` up to (but not including) `limit`.
- Returns the list of squares.

**Example:**
```python
squares_of_odds(10)
```
**Expected Output:** `[1, 9, 25, 49, 81]`


In [21]:
def squares_of_odds(limit):
  squares_of_odds = []
  for num in range (limit):
    if num %2 !=0:
      odd_number = num **2
      squares_of_odds.append(odd_number)


  return squares_of_odds




squares_of_odds(10)


[1, 9, 25, 49, 81]

In [ ]:
def squares_of_odds(limit):
    '''your code'''



print(squares_of_odds(10))

### Task 1.6: Map - Convert Temperature from Celsius to Fahrenheit
Write a function `convert_to_fahrenheit(celsius_list)` that:
- Takes a list of temperatures in Celsius (`celsius_list`) as an argument.
- Uses `map()` to convert each temperature to Fahrenheit using the formula: `F = C * 9/5 + 32`.
- Returns a list of the converted Fahrenheit values.

**Example:**
```python
convert_to_fahrenheit([0, 25, 30, 100])
```
**Expected Output:** `[32.0, 77.0, 86.0, 212.0]`

In [ ]:
def convert_to_fahrenheit(celsius_list):
    '''your code'''



print(convert_to_fahrenheit([0, 25, 30, 100]))



### Task 1.7: Filter - Words Longer than 5 Characters
Write a function `long_words(words)` that:
- Takes a list of strings `words` as an argument.
- Uses `filter()` to return a list of only the words that are longer than 5 characters.

**Example:**
```python
long_words(['apple', 'banana', 'kiwi', 'strawberry', 'pear'])
```
**Expected Output:** `['banana', 'strawberry']`
```


In [ ]:
def long_words(words):
    '''your code'''


print(long_words(['apple', 'banana', 'kiwi', 'strawberry', 'pear']))


# Task 2: NumPy

## Part 1: Creating Matrices

### 2.1 Random Integer Matrix
Write a function `random_integer_matrix(rows, cols, low, high)` that:
- Takes four arguments: `rows`, `cols`, `low`, and `high`.
- Uses `np.random.randint()` to create a matrix of shape `(rows, cols)` filled with random integers between `low` (inclusive) and `high` (exclusive).
- Returns the created matrix.

**Example:**
```python
random_integer_matrix(3, 4, 1, 10)
```

**Expected Output:**
```
([[4, 1, 7, 2],
 [3, 9, 5, 6],
 [8, 2, 3, 4]])
```

In [ ]:
import numpy as np

In [ ]:
def random_integer_matrix(rows, cols, low, high):
    '''your code'''



result = random_integer_matrix(3, 4, 1, 10)
print(result)


### 2.2 Linear Space Matrix
Write a function `linear_space_matrix(start, stop, num)` that:
- Takes three arguments: `start`, `stop`, and `num`.
- Uses `np.linspace()` to create a 1D array of `num` evenly spaced values between `start` and `stop`.
- Reshape the array into a 2D matrix with shape `(num, 1)` and return it.

**Example:**
```python
linear_space_matrix(0, 1, 5)
```

**Expected Output:**
```
array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])
```


In [ ]:
def linear_space_matrix(start, stop, num):
    '''your code'''


# Example usage:
result = linear_space_matrix(0, 1, 5)
print(result)


## Part 2: Indexing and Slicing

### 2.3 Row and Column Slicing
Write a function `slice_matrix(matrix)` that:
- Takes a 2D NumPy array `matrix` as an argument.
- Returns the second row and the first column of the matrix.

**Example:**
```python
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_matrix(matrix)
```

**Expected Output:**
```
Second row: [4, 5, 6]
First column: [1, 4, 7]
```

In [ ]:
def slice_matrix(matrix):
    '''your code'''
    return None, None



matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_row, first_column = slice_matrix(matrix)
print("Second row:", second_row)
print("First column:", first_column)


### 2.4 Conditional Indexing
Write a function `conditional_filter(matrix)` that:
- Takes a 2D NumPy array `matrix` as an argument.
- Returns a 1D array containing all values greater than a specified threshold (e.g., `5`).

**Example:**
```python
import numpy as np
matrix = np.array([[1, 6, 3], [8, 5, 7], [2, 10, 9]])
conditional_filter(matrix)
```

**Expected Output:**
```
array([ 6,  8,  7, 10,  9])
```


In [ ]:
def conditional_filter(matrix, threshold = 5):
    '''your code'''



matrix = np.array([[1, 6, 3], [8, 5, 7], [2, 10, 9]])
result = conditional_filter(matrix)
print(result)


## Part 3: Matrix Operations


### 2.5: Matrix Multiplication with Dimension Check and Error Handling

#### Problem Statement
Write a function `multiply_matrices(A, B)` that:
- Takes two 2D NumPy arrays `A` and `B` as arguments.
- Checks the dimensions:
  - If the matrices are compatible, multiply them using both the `@` operator and `np.dot()`.
  - If not compatible, check if transposing either matrix could work. If still incompatible, print an error message.

**Example:**
```python
      A = np.array([[1, 2], [3, 4]])
      B = np.array([[5, 6], [7, 8]])
      result = multiply_matrices(A, B)
```

**Expected Output:**
For compatible dimensions:
```plaintext
Result using @ operator:
 [[19 22]
 [43 50]]
Result using np.dot:
 [[19 22]
 [43 50]]
```

For incompatible dimensions:
```plaintext
Error: Incompatible dimensions for matrix multiplication.
```



In [ ]:
def multiply_matrices(A, B):
    '''your code'''
    return None, None

# Example usage:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = multiply_matrices(A, B)

if result[0] is not None:
    print("Result using @ operator:\n", result[0])
    print("Result using np.dot:\n", result[1])

# Example with needed tanspose
C = np.array([[5, 6, 7], [8, 9, 10]])
result_T = multiply_matrices(A, C)

if result_T[0] is not None:
    print("Result using @ operator:\n", result_T[0])
    print("Result using np.dot:\n", result_T[1])

# Example with incompatible dimensions
D = np.array([[1,2,3],[5, 6, 7], [8, 9, 10]])
multiply_matrices(A, D)  # Should print an error



### 2.6 Calculating Mean and Logical Operations
Write a function `mean_and_filter(matrix)` that:
- Takes a 2D NumPy array `matrix` as an argument.
- Calculates the mean of each row using `np.mean()`.
- Applies a logical condition using `np.logical_and()` to filter values that are:
    - Greater than the mean of the respective rows.
    - Less than the specified 'upper_limit'.

**Example:**
```python
import numpy as np
matrix = np.array([[1, 6, 3], [8, 5, 7], [2, 10, 9]])
mean_and_filter(matrix)
```

**Expected Output:**
```
Row means: [3.33333333 6.66666667 7.        ]
Filtered values: [array([6]), array([8, 7]), array([])]

```

In [ ]:
def mean_and_filter(matrix, upper_limit):
    '''your code'''
    return None, None

# Example usage:
matrix = np.array([[1, 6, 3], [8, 5, 7], [2, 10, 9]])
upper_limit = 9
means, filtered = mean_and_filter(matrix, upper_limit)
print("Row means:", means)
print("Filtered values:", filtered)


# Task 3: Plotting with Matplotlib

### 3.1 Plotting a Function

Write a function `plot_sine_wave(start, stop, num_points)` that:
- Takes three arguments: `start`, `stop`, and `num_points`.
- Creates a sine wave using `np.sin` over a range of values from `start` to `stop` with `num_points` points.
- Plots the sine wave using `plt.plot()` and customizes the plot with a title, labeled axes, and a grid.

**Example Usage:**
```python
plot_sine_wave(0, 2 * np.pi, 100)
```

**Expected Plot:**
- A smooth sine wave from $0$ to $2\pi$, with labeled axes and a grid.



In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def plot_sine_wave(start, stop, num_points):
    '''your code'''


# Example usage
plot_sine_wave(0, 2 * np.pi, 100)



### 3.2 Plotting and Calculating the Area Under a Curve

Write a function `plot_parabola_with_integral(a, b)` that:
- Takes two arguments, `a` and `b`, which define the interval $[a, b]$.
- Defines a function $ f(x) = x^2 $.
- Plots $ f(x) $ over the interval $[a, b]$ and shades the area under the curve.
- Calculates the area using `scipy.integrate.quad()` and displays it on the plot.

**Example Usage:**
```python
plot_parabola_with_integral(0, 3)
```

**Expected Plot and Output:**
- A plot of $f(x) = x^2 $ from $0$ to $3$, with the area under the curve shaded.
- Display the calculated area as text on the plot.



In [ ]:
from scipy.integrate import quad

In [ ]:
def plot_parabola_with_integral(a, b):
    '''your code'''


# Example usage
plot_parabola_with_integral(0, 3)





### 3.3 Scatter Plot and Histogram

Write a function `scatter_and_histogram(num_points)` that:
- Takes `num_points` as an argument.
- Generates `num_points` random data points for both `x` and `y` coordinates using `np.random.randn()`.
- Creates a scatter plot for `x` and `y` values.
- Plots a histogram of the `x` values on a separate subplot.

**Example Usage:**
```python
scatter_and_histogram(100)
```

**Expected Plot:**
- A scatter plot with random data points on one subplot.
- A histogram showing the distribution of `x` values on another subplot.



In [ ]:
def scatter_and_histogram(num_points):
    '''your code'''


# Example usage
scatter_and_histogram(100)


### 3.4 Overlaying Plots with Contour

Write a function `contour_with_distribution_overlay()` that:
- Creates a 2D grid of values for $x$ and $y$.
- Defines a Gaussian-like 2D function $f(x, y) = e^{-(x^2 + y^2)}$.
- Plots a contour plot of $f(x, y)$.
- Adds an overlaid line plot of a 1D Gaussian distribution (e.g., $ g(x) = e^{-x^2} $) along the $x$-axis for visual comparison.

**Example Usage:**
```python
contour_with_distribution_overlay()
```

**Expected Plot:**
- A contour plot of $f(x, y)$ with an overlaid line plot representing a Gaussian distribution along the $x$-axis.

In [ ]:
def contour_with_distribution_overlay():
    '''your code'''


# Example usage
contour_with_distribution_overlay()


# Task 4: Broadcasting in NumPy

Before working on these exercises make yourself familiar with the concept of [broadcasting in NumPy](https://numpy.org/devdocs/user/basics.broadcasting.html).
### 4.1 Scalar and Array Broadcasting

Write a function `add_scalar_to_array(arr, scalar)` that:
- Takes an array `arr` and a scalar `scalar`.
- Adds the scalar to each element in `arr` using broadcasting.
- Returns the result.

**Example Usage:**
```python
arr = np.array([1, 2, 3, 4])
add_scalar_to_array(arr, 5)
```

**Expected Output:**
```
array([6, 7, 8, 9])
```




In [ ]:
def add_scalar_to_array(arr, scalar):
    '''your code'''


# Example usage:
arr = np.array([1, 2, 3, 4])
result = add_scalar_to_array(arr, 5)
print("Result:", result)


### 4.2 Row-wise and Column-wise Operations

Write a function `row_column_operations(matrix, row_vector, column_vector)` that:
- Takes a 2D NumPy array `matrix`, a 1D `row_vector`, and a 1D `column_vector`.
- Adds `row_vector` to each row of `matrix` and `column_vector` to each column of `matrix` using broadcasting.
- Returns the resulting matrix after both operations.

**Example Usage:**
```python
matrix = np.array([[1, 2], [3, 4]])
row_vector = np.array([10, 20])
column_vector = np.array([5, 15])
row_column_operations(matrix, row_vector, column_vector)
```

**Expected Output:**
```
array([[16, 27],
       [28, 39]])
```

In [ ]:
def row_column_operations(matrix, row_vector, column_vector):
     '''your code'''


# Example usage:
matrix = np.array([[1, 2], [3, 4]])
row_vector = np.array([10, 20])
column_vector = np.array([5, 15])
result = row_column_operations(matrix, row_vector, column_vector)
print("Result:\n", result)



### 4.3 Element-wise Operations with Different Shapes

Write a function `elementwise_product_with_column(matrix, column_vector)` that:
- Takes a 2D NumPy array `matrix` and a 1D NumPy array `column_vector`.
- Multiplies each row of the `matrix` by the corresponding element in `column_vector` (using broadcasting).
- Returns the resulting matrix.

**Example Usage:**
```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_vector = np.array([1, 2, 3])
elementwise_product_with_column(matrix, column_vector)
```

**Expected Output:**
```
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])
```



In [ ]:
def elementwise_product_with_column(matrix, column_vector):
    '''your code'''


# Example usage
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_vector = np.array([1, 2, 3])
result = elementwise_product_with_column(matrix, column_vector)
print(result)



### 4.4: Normalizing Rows in a Matrix

Write a function `normalize_rows(matrix)` that:
- Takes a 2D NumPy array `matrix`.
- Computes the sum of each row and then normalizes each row by dividing each element by the row’s sum (using broadcasting).
- Returns the row-normalized matrix.

**Example Usage:**
```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
normalize_rows(matrix)
```

**Expected Output:**
```
array([[0.1667, 0.3333, 0.5   ],
       [0.2667, 0.3333, 0.4   ],
       [0.2917, 0.3333, 0.375 ]])
```



These tasks build upon the first two exercises, leading into complex applications and setting a foundation for understanding broadcasting with probability tables in the upcoming Bayesian Network exercise. Let me know when you’re ready to see the solutions for these!

In [ ]:
def normalize_rows(matrix):
    '''your code'''


# Example usage
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
normalized_result = normalize_rows(matrix)
print(normalized_result)
